services:
  postgres:
    container_name: week5
    image: 'postgres:latest'
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      PGDATA: /data/postgres
    ports:
      - "5444:5432"

    restart: always

volumes:
  db:
